version: '3.3'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
  notee:
    image: localhost:5000/avabhyankar/notes-app:latest
    container_name: notes-app-1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres/postgres
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
      SPRING_SQL_INIT_MODE: always
      SPRING_LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
      SPRINGDOC_PACKAGES_TO_SCAN: com.arth.notee
      SPRINGDOC_VERSION: '1.0.0'